-- MySQL Script generated by MySQL Workbench
-- 04/12/14 17:13:09
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema adonatac_changas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `adonatac_changas` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `adonatac_changas` ;

-- -----------------------------------------------------
-- Table `adonatac_changas`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adonatac_changas`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  `first_name` VARCHAR(100) NULL,
  `last_name` VARCHAR(100) NULL,
  `genero` VARCHAR(6) NULL,
  `email` VARCHAR(60) NULL,
  `username` VARCHAR(50) NULL,
  `Usuarioscol` VARCHAR(45) NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adonatac_changas`.`publicaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adonatac_changas`.`publicaciones` (
  `id_publicacion` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  `tarea` VARCHAR(256) NULL,
  `cuando` DATETIME NULL,
  `precio` DOUBLE NULL,
  `publicacionescol` VARCHAR(45) NULL,
  PRIMARY KEY (`id_publicacion`),
  INDEX `usr_publicaciones_idx` (`id_usuario` ASC),
  CONSTRAINT `usr_publicaciones`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `adonatac_changas`.`usuarios` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adonatac_changas`.`postulaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adonatac_changas`.`postulaciones` (
  `id_postulacion` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  `id_publicacion` INT NOT NULL,
  `date` DATETIME NULL,
  `nota` VARCHAR(250) NULL,
  PRIMARY KEY (`id_postulacion`),
  INDEX `post_usuarios_idx` (`id_usuario` ASC),
  INDEX `post_public_idx` (`id_publicacion` ASC),
  CONSTRAINT `post_usuarios`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `adonatac_changas`.`usuarios` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `post_public`
    FOREIGN KEY (`id_publicacion`)
    REFERENCES `adonatac_changas`.`publicaciones` (`id_publicacion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adonatac_changas`.`valoraciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adonatac_changas`.`valoraciones` (
  `id_valoracion` INT NOT NULL,
  `id_usuario_remitente` INT NULL,
  `id_usuario_destinatario` INT NULL,
  `calificacion` INT NULL,
  `nota` VARCHAR(256) NULL,
  PRIMARY KEY (`id_valoracion`),
  INDEX `valora_usuar_from_idx` (`id_usuario_remitente` ASC),
  INDEX `valora_from_to_idx` (`id_usuario_destinatario` ASC),
  CONSTRAINT `valora_usuar_from`
    FOREIGN KEY (`id_usuario_remitente`)
    REFERENCES `adonatac_changas`.`usuarios` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `valora_from_to`
    FOREIGN KEY (`id_usuario_destinatario`)
    REFERENCES `adonatac_changas`.`usuarios` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adonatac_changas`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adonatac_changas`.`tags` (
  `id_tag` INT NOT NULL,
  `description` VARCHAR(50) NULL,
  PRIMARY KEY (`id_tag`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adonatac_changas`.`publicacion_tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adonatac_changas`.`publicacion_tags` (
  `id_publicacion` INT NOT NULL,
  `id_tag` INT NULL,
  PRIMARY KEY (`id_publicacion`),
  INDEX `ptags_tags_idx` (`id_tag` ASC),
  CONSTRAINT `ptags_publicacion`
    FOREIGN KEY (`id_publicacion`)
    REFERENCES `adonatac_changas`.`publicaciones` (`id_publicacion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ptags_tags`
    FOREIGN KEY (`id_tag`)
    REFERENCES `adonatac_changas`.`tags` (`id_tag`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
